insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Artur Clavering', '1995-05-28', 'Rite Aid Sunscreen', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Marylee Neem', '1998-11-29', 'HYDROCORTISONE', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Sky Haxley', '2003-02-04', 'IRINOTECAN HYDROCHLORIDE', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Bradan Kilfether', '2000-08-07', 'Losartan Potassium and Hydrochlorothiazide', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Brose Dayne', '1995-04-04', 'migraine formula', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Aleda Stollberg', '1991-03-08', 'VETERAN SHIELD 24', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Murdock Ruspine', '1995-01-21', 'SMART SENSE', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Travus McCloy', '2002-01-06', 'MARCS', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Anna-maria Kneath', '2003-03-24', 'Healthy Accents Muscle Rub', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Silvan Treanor', '1996-01-25', 'Clonidine Hydrochloride', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Glen Clowton', '1995-06-30', 'Cefepime', '60');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Sauveur Ashmole', '1991-08-18', 'dayhist allergy', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Lottie Longina', '2000-03-17', 'Synthroid', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Woodrow Crowcum', '1999-09-15', 'Delsym', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Falito Micheau', '2002-09-27', 'LBEL', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Shelley Wicher', '2004-03-16', 'LANOXIN', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Pembroke Vane', '1995-02-28', 'Lysol', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Jeanie Bartke', '1991-03-04', 'PANTOPRAZOLE SODIUM', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Hermine Ohm', '2003-12-28', 'TAZ204C', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Barn Garthside', '2005-11-26', 'smart sense allergy and congestion relief', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Gracie Sieghard', '2003-09-09', 'Medi First Plus Non-Aspirin', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Harland Twiname', '1992-11-10', 'LOVAZA', '6');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Phoebe Lanston', '1995-09-15', 'Lisinopril', '18');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Angie O''Hederscoll', '1991-11-13', 'INSTA-CHAR AQUEOUS CHERRY', '18');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Feliza Pieroni', '1991-12-12', 'Laneige Sliding Pact EX', '18');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Colin Wigmore', '2003-03-11', 'Sulfamethoxazole and Trimethoprim', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Rhett Hilbourne', '1997-03-17', 'Clear Proof Acne Treatment', '18');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('6h Seaton', '2005-04-14', 'LEMON', '18');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Lillian Purrier', '1995-08-13', 'Ammonia Inhalants', '18');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Giraud McQuode', '2003-06-09', 'Naproxen Sodium', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Hartwell Fogden', '2004-12-04', 'Neosporin Eczema Essentials', '18');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Rubina Dovidian', '1998-06-04', 'Brioschi Childrens Effervescent Antacid', '4');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Adella Yonge', '2002-10-04', 'BioTPres', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Denna Upstone', '1993-07-06', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', '4');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Danny Kelland', '2004-10-29', 'Type 3 Sinus Max', '4');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Franciska Dumingo', '2005-07-09', 'ROCKY MOUNTAIN JUNIPER POLLEN', '4');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Veradis Ogelbe', '1996-11-29', 'Anticoagulant Citrate Dextrose A', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Vergil Puttick', '1995-04-02', 'Mirtazapine', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Leyla Teck', '1991-05-01', 'Ceftriaxone Sodium', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Robinette Syne', '1995-11-21', 'Oxygen', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Steve Pott', '1993-02-04', 'Regimen', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Cherise Stockford', '1992-05-07', 'FOAMING HAND SANITIZER', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Livy Hintze', '1991-04-17', 'Bio-B Kids', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Ambrosius Pearman', '1994-02-24', 'Natures Gate', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Cecile Flather', '2000-08-05', 'Bio Gorse', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Wanda Woollaston', '1992-06-18', 'Hydrochlorothiazide', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Sonny Haycroft', '1998-10-22', 'Certus Sting Relief Prep Pad', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Anya Dungee', '2002-09-23', 'AMITRIPTYLINE HYDROCHLORIDE', '2');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Michal Kalkofer', '1991-10-04', 'PediaCare Infants Fever Reducer Cherry', '29');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Sherri Himpson', '1992-10-02', 'retaine MGD', '29');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Franny Hengoed', '1992-11-07', 'DARANIDE', '29');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Robinette Lamar', '1994-03-22', 'Hydrogen Peroxide', '29');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Ritchie Drover', '1998-11-18', 'LEVOFLOXACIN', '29');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Thatcher Dunniom', '2001-05-28', 'Adaptagen', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Thomas Masterson', '1992-03-02', 'Nite Time Cold and Flu Relief', '29');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Cheryl Ingham', '1991-06-09', 'Berry Scented Hand Sanitizer', '29');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Cy Breach', '2005-10-07', 'Yellow Dock', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Anet Helks', '1994-04-22', 'Lidocaine Hydrochloride and Epinephrine', '33');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Rakel Goomes', '2003-03-23', 'PAROXETINE', '33');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Andonis Mercik', '1998-06-26', 'Lovenox', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Seward Sprakes', '1991-07-07', 'hydroxyzine pamoate', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Kesley Dallimore', '1996-09-24', 'Metoclopramide', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Phip Burgen', '1995-10-26', 'BLATELLA GERMANICA', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Loree Shimon', '1996-03-12', 'Multi-Symptom Mapap Cold Formula', '33');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Trace Ubach', '2002-11-05', 'Metoclopramide Hydrochloride', '33');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Ashely Leyband', '2000-02-27', 'ShopRite Ni Calm', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Nara Babington', '1994-01-14', 'HAND AND NATURE SANITIZER', '33');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Brooke Baron', '1993-08-25', 'Lisinopril', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Case Anthoney', '2001-12-13', 'Fusarium compactum', '33');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('D204lynne Grannell', '2004-09-07', 'ESIKA', '33');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Ag Hubbold', '1991-12-02', 'Cefuroxime Axetil', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Stormie Cowmeadow', '2002-01-16', 'Probiotic Rest204tion', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Giulio Garham', '2000-12-31', 'Cotton', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Meier Worrill', '2003-10-08', 'Fentanyl Citrate, Bupivacaine HCl', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Ignace Feirn', '1998-08-07', 'Cortomycin', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('29 Tilt', '1994-03-27', 'Cold and Flu Nighttime', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Tiff Baiden', '2003-08-21', 'triple antibiotic', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Lebbie Insko', '1998-05-12', 'Valacyclovir Hydrochloride', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Suzanne Pothergill', '2003-12-05', 'Cetirizine Hydrochloride', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Belle Kibbe', '2004-06-02', 'ATOMY SUN CREAM SPF 50 PA', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Corine Gittings', '1997-11-27', 'Urecholine', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Alis Wadeling', '2000-06-28', 'Dr. JIs Arthritis Plus', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Meryl Strutt', '2001-02-28', 'Macular Degeneration', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Thibaud Sch204h', '1998-04-24', 'Notatum', '49');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Janka Dyas', '1996-04-29', 'SUPER SERUM', '70');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Jerome Bucklan', '1998-01-08', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', '70');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Mahmoud Olman', '1996-04-29', 'Shagbark Hickory', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Ruthanne Flindall', '2000-10-21', 'PCE', '70');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Tomi MacGillespie', '2003-04-20', 'CARBAMAZEPINE', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Fabian Gavigan', '1996-07-24', 'Nu Skin Sunright 35 Broad Spectrum SPF 35', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Hugo Burvill', '2000-02-13', 'SmartRx Natural Pain Relief Sleeve BACK', '70');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Herschel Rosenthaler', '1993-03-22', 'Tension Headache Relief', '70');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Virginie Foulcher', '1994-12-12', 'Omeprazole', '70');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Clemente Underdown', '1996-05-07', 'Teveten', '70');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Shellysheldon Bradnam', '2000-10-19', 'BANDAGE', null);
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Veronique Grigs', '2002-01-28', 'Azithromycin', '70');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Michele Buesden', '2003-03-16', 'Flurbiprofen', '75');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Hector Bligh', '1997-06-17', 'NAPROXEN', '75');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Vina Toon', '1998-02-14', 'Methyldopa and Hydrochlorothiazide', '75');
insert into amir_music_musico (nombre, fecha_nacimiento, instrumento, grupo_id) values ('Jenni Kid', '2000-02-09', 'Dial Complete Antibacterial Foaming Hand Washkitchen crisp limkitchen crisp lim', '75');
